import 'dotenv/config';import bcrypt from 'bcryptjs';import {connectDB} from '../config/db.js';import Admin from '../models/Admin.js';import Product from '../models/Product.js';
const imgs={resin:'https://images.pexels.com/photos/6858596/pexels-photo-6858596.jpeg?auto=compress&cs=tinysrgb&w=900',resin2:'https://images.pexels.com/photos/16110426/pexels-photo-16110426.jpeg?auto=compress&cs=tinysrgb&w=900',resin3:'https://images.pexels.com/photos/17225139/pexels-photo-17225139.jpeg?auto=compress&cs=tinysrgb&w=900',key:'https://images.pexels.com/photos/15679987/pexels-photo-15679987.jpeg?auto=compress&cs=tinysrgb&w=900',key2:'https://images.pexels.com/photos/15955322/pexels-photo-15955322.jpeg?auto=compress&cs=tinysrgb&w=900',book:'https://images.pexels.com/photos/20092857/pexels-photo-20092857.jpeg?auto=compress&cs=tinysrgb&w=900',book2:'https://images.pexels.com/photos/20092846/pexels-photo-20092846.jpeg?auto=compress&cs=tinysrgb&w=900',book3:'https://images.pexels.com/photos/23884956/pexels-photo-23884956.jpeg?auto=compress&cs=tinysrgb&w=900',book4:'https://images.pexels.com/photos/29391653/pexels-photo-29391653.jpeg?auto=compress&cs=tinysrgb&w=900'};
const products=[
['Floral Resin Keychain','keychains',300,600,imgs.resin,'A clear resin charm with botanical-inspired detail.',24,true,true],['Ocean Wave Keychain','keychains',300,600,imgs.key,'A deep ocean-inspired keychain for everyday carry.',18,true,true],['Golden Bloom Keychain','keychains',300,600,imgs.resin2,'Warm gold and floral styling with a glossy finish.',20,true,true],['Minimal Round Keychain','keychains',300,600,imgs.key2,'Clean round silhouette for a timeless handmade look.',15,false,true],['Initial Name Keychain','custom',600,900,imgs.resin3,'Personalized initial or name design made to order.',30,true,true],['Photo Memory Keychain','custom',600,900,imgs.key,'Turn a favorite photo into a keepsake charm.',12,true,true],['Two-Sided Custom Keychain','custom',600,900,imgs.resin2,'Two-sided personalization with artwork on both faces.',10,true,true],['Pressed Flower Bookmark','bookmarks',300,600,imgs.book,'Transparent botanical bookmark with a premium tassel.',20,true,true],['Gold Flake Bookmark','bookmarks',300,600,imgs.book2,'Clear resin bookmark finished with gold-flake detail.',22,true,true],['Blue Floral Bookmark','bookmarks',300,600,imgs.book3,'Soft blue botanical bookmark for readers and gifting.',17,false,true],['Classic Flower Bookmark','bookmarks',300,600,imgs.book4,'Elegant floral bookmark with a clean handmade finish.',16,false,true],['Custom Quote Bookmark','custom',600,900,imgs.book3,'Add a name, quote or short message to your bookmark.',14,true,true]
].map(([name,category,price,customPrice,image,description,stock,featured,customizable],i)=>({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+i,category,price,customPrice,description,images:[image],stock,featured,customizable,available:true}));
await connectDB();
await Product.deleteMany({});await Product.insertMany(products);
if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD){const passwordHash=await bcrypt.hash(process.env.ADMIN_PASSWORD,12);await Admin.findOneAndUpdate({email:process.env.ADMIN_EMAIL.toLowerCase()},{email:process.env.ADMIN_EMAIL.toLowerCase(),passwordHash,role:'admin'},{upsert:true,new:true,setDefaultsOnInsert:true});console.log('Admin seeded:',process.env.ADMIN_EMAIL)}else console.log('Set ADMIN_EMAIL and ADMIN_PASSWORD before seeding admin');
process.exit(0);
